name: twitter_1user
description: Connect to Twitter API with OAuth1.0a. The access token is assumed to be obtained from the Twitter application details page. It is therefore ideal for single user applications.
version: 1.0.0
homepage: https://github.com/edo1z/twitter_1user
author: edo1z <endo.yuta@logicky.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  convert: ^2.1.1
  crypto: ^2.1.2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
